basePath: /api
definitions:
  user.CreateUserRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  user.UserPresenter:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact:
    email: minghsu0107@gmail.com
    name: Ming Hsu
  description: User service API
  title: User Service Swagger API
  version: "2.0"
paths:
  /user:
    post:
      description: Register a new user
      parameters:
      - description: new user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/user.UserPresenter'
        "400":
          description: Bad Request
          schema:
            type: none
        "500":
          description: Internal Server Error
          schema:
            type: none
      summary: Create an user
      tags:
      - user
  /user/{uid}/name:
    get:
      description: Get user name
      parameters:
      - description: user id
        in: path
        name: uid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserPresenter'
        "400":
          description: Bad Request
          schema:
            type: none
        "404":
          description: Not Found
          schema:
            type: none
        "500":
          description: Internal Server Error
          schema:
            type: none
      summary: Get user name
      tags:
      - user
swagger: "2.0"
