basePath: /api
definitions:
  common.ErrResponse:
    properties:
      msg:
        type: string
    type: object
  common.SuccessMessage:
    properties:
      msg:
        example: ok
        type: string
    type: object
  user.CreateUserRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  user.UserPresenter:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact:
    email: minghsu0107@gmail.com
    name: Ming Hsu
  description: User service API
  title: User Service Swagger API
  version: "2.0"
paths:
  /user:
    get:
      description: Get user information
      parameters:
      - description: target user id; defaults to self user id if leaved empty
        in: query
        name: uid
        type: string
      - description: session id cookie
        in: header
        name: Cookie
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserPresenter'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/common.ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrResponse'
      summary: Get user
      tags:
      - user
    post:
      description: Register a new user
      parameters:
      - description: new user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/user.UserPresenter'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrResponse'
      summary: Create an user
      tags:
      - user
  /user/oauth2/google/callback:
    get:
      description: OAuth Google callback endpoint
      responses:
        "307":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrResponse'
      summary: OAuth Google callback
      tags:
      - user
  /user/oauth2/google/login:
    get:
      description: OAuth Google login endpoint
      responses:
        "307":
          description: ""
      summary: OAuth Google login
      tags:
      - user
swagger: "2.0"
