web:
  http:
    server:
      port: "80"
chat:
  http:
    server:
      port: "80"
      maxConn: 200
      swag: true
  grpc:
    server:
      port: "4000"
    client:
      user:
        endpoint: "localhost:4001"
  message:
    maxNum: 5000
    paginationNum: 5000
    maxSizeByte: 4096
  jwt:
    secret: mysecret
    expirationSecond: 86400
match:
  http:
    server:
      port: "80"
      maxConn: 200
      swag: true
  grpc:
    client:
      chat:
        endpoint: "localhost:4000"
      user:
        endpoint: "localhost:4001"
uploader:
  http:
    server:
      port: "80"
      swag: true
      maxBodyByte: 67108864
      maxMemoryByte: 16777216
  s3:
    endpoint: http://localhost:9000
    region: us-east-1
    bucket: myfilebucket
    accessKey: testaccesskey
    secretKey: testsecret
user:
  http:
    server:
      port: "80"
      swag: true
  grpc:
    server:
      port: "4001"
  oauth:
    cookie:
      maxAge: 3600
      path: "/"
      domain: "localhost"
    google:
      redirectUrl: "http://localhost/api/user/oauth2/google/callback"
      clientId: ""
      clientSecret: ""
      scopes: "https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/userinfo.profile"
  auth:
    cookie:
      maxAge: 86400
      path: "/"
      domain: "localhost"
kafka:
  addrs: kafka-0:9092,kafka-1:9092,kafka-2:9092
  version: "3.0.1"
cassandra:
  hosts: cassandra-host-0,cassandra-host-1,cassandra-host-2
  port: 9042
  user: cassandra
  password: cassandra
  keyspace: randomchat
redis:
  password: pass.123
  addrs: redis-node-0:6379,redis-node-1:6379,redis-node-2:6379
  expirationHour: 24
  minIdleConn: 30
  poolSize: 500
  readTimeoutMilliSecond: 500
  writeTimeoutMilliSecond: 500
observability:
  prometheus:
    port: "8080"
  tracing:
    jaegerUrl: "http://localhost:14268/api/traces"
