basePath: /api
definitions:
  common.ErrResponse:
    properties:
      msg:
        type: string
    type: object
info:
  contact:
    email: minghsu0107@gmail.com
    name: Ming Hsu
  description: Match service API
  title: Match Service Swagger API
  version: "2.0"
paths:
  /match:
    get:
      description: Websocket initialization endpoint for matching another user
      parameters:
      - description: session id cookie
        in: header
        name: Cookie
        required: true
        type: string
      produces:
      - application/json
      responses:
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/common.ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrResponse'
      summary: Match another user
      tags:
      - match
  /match/forwardauth:
    get:
      description: Traefik forward auth endpoint for channel authentication
      parameters:
      - description: channel authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: none
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/common.ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrResponse'
      summary: Forward auth
      tags:
      - match
swagger: "2.0"
